'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Reflection

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class ClassNames
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SkyEditor.SaveEditor.ClassNames", GetType(ClassNames).GetTypeInfo.Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Binary File.
        '''</summary>
        Public Shared ReadOnly Property SkyEditor_SaveEditor_BinaryFile() As String
            Get
                Return ResourceManager.GetString("SkyEditor_SaveEditor_BinaryFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Active Pokemon (Explorers of Sky).
        '''</summary>
        Public Shared ReadOnly Property SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkyActivePokemon() As String
            Get
                Return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkyActivePokemon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quicksave Pokemon (Explorers of Sky).
        '''</summary>
        Public Shared ReadOnly Property SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkyQuicksavePokemon() As String
            Get
                Return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkyQuicksavePokemon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explorers of Sky Save File.
        '''</summary>
        Public Shared ReadOnly Property SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkySave() As String
            Get
                Return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkySave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stored Pokemon (Explorers of Sky).
        '''</summary>
        Public Shared ReadOnly Property SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkyStoredPokemon() As String
            Get
                Return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkyStoredPokemon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Active Pokemon (Explorers of Time and Darkness).
        '''</summary>
        Public Shared ReadOnly Property SkyEditor_SaveEditor_MysteryDungeon_Explorers_TDActivePokemon() As String
            Get
                Return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_TDActivePokemon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explorers of Time and Darkness Save File.
        '''</summary>
        Public Shared ReadOnly Property SkyEditor_SaveEditor_MysteryDungeon_Explorers_TDSave() As String
            Get
                Return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_TDSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stored Pokemon (Explorers of Time and Darkness).
        '''</summary>
        Public Shared ReadOnly Property SkyEditor_SaveEditor_MysteryDungeon_Explorers_TDStoredPokemon() As String
            Get
                Return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_TDStoredPokemon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Red and Blue Rescue Team Save File (North America).
        '''</summary>
        Public Shared ReadOnly Property SkyEditor_SaveEditor_MysteryDungeon_Rescue_RBSave() As String
            Get
                Return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Rescue_RBSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Red and Blue Rescue Team Save File (Europe).
        '''</summary>
        Public Shared ReadOnly Property SkyEditor_SaveEditor_MysteryDungeon_Rescue_RBSaveEU() As String
            Get
                Return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Rescue_RBSaveEU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stored Pokemon (Red and Blue Rescue Team).
        '''</summary>
        Public Shared ReadOnly Property SkyEditor_SaveEditor_MysteryDungeon_Rescue_RBStoredPokemon() As String
            Get
                Return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Rescue_RBStoredPokemon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gates to Infinity game_data File (Experimental).
        '''</summary>
        Public Shared ReadOnly Property SkyEditor_SaveEditor_Saves_GTIGameData() As String
            Get
                Return ResourceManager.GetString("SkyEditor_SaveEditor_Saves_GTIGameData", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
