//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyEditor.SaveEditor.UI.Avalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyEditor.SaveEditor.UI.Avalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Views_Explorers_Add {
            get {
                return ResourceManager.GetString("Views_Explorers_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contained Item.
        /// </summary>
        public static string Views_Explorers_ContainedItem {
            get {
                return ResourceManager.GetString("Views_Explorers_ContainedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string Views_Explorers_NewItem {
            get {
                return ResourceManager.GetString("Views_Explorers_NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity
        ///
        ///For stackable items like sticks and spikes, this lets you control how much is in this stack.  This is ignored for non-stackable items..
        /// </summary>
        public static string Views_Explorers_NewItemQuantityTooltip {
            get {
                return ResourceManager.GetString("Views_Explorers_NewItemQuantityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventures.
        /// </summary>
        public static string Views_Explorers_Sky_Adventures {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_Adventures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Rescue Held Items.
        /// </summary>
        public static string Views_Explorers_Sky_FriendRescueHeldItemsTab {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_FriendRescueHeldItemsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Views_Explorers_Sky_GeneralTab {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Held Items.
        /// </summary>
        public static string Views_Explorers_Sky_HeldItemsTab {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_HeldItemsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Held Money.
        /// </summary>
        public static string Views_Explorers_Sky_HeldMoney {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_HeldMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Views_Explorers_Sky_HistoryTab {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_HistoryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Views_Explorers_Sky_InventoryTab {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_InventoryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Female.
        /// </summary>
        public static string Views_Explorers_Sky_IsFemale {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_IsFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Partner Gender.
        /// </summary>
        public static string Views_Explorers_Sky_OriginalPartnerGender {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_OriginalPartnerGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Partner Name.
        /// </summary>
        public static string Views_Explorers_Sky_OriginalPartnerName {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_OriginalPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Partner Pokémon.
        /// </summary>
        public static string Views_Explorers_Sky_OriginalPartnerPkm {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_OriginalPartnerPkm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Player Gender.
        /// </summary>
        public static string Views_Explorers_Sky_OriginalPlayerGender {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_OriginalPlayerGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Player Name.
        /// </summary>
        public static string Views_Explorers_Sky_OriginalPlayerName {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_OriginalPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Player Pokémon.
        /// </summary>
        public static string Views_Explorers_Sky_OriginalPlayerPkm {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_OriginalPlayerPkm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank Points.
        /// </summary>
        public static string Views_Explorers_Sky_RankPoints {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_RankPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sp. Episode Held Items.
        /// </summary>
        public static string Views_Explorers_Sky_SpEpisodeHeldItemsTab {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_SpEpisodeHeldItemsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sp. Episode Held Money.
        /// </summary>
        public static string Views_Explorers_Sky_SpEpisodeHeldMoney {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_SpEpisodeHeldMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Items.
        /// </summary>
        public static string Views_Explorers_Sky_StoredItemsTab {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_StoredItemsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Money.
        /// </summary>
        public static string Views_Explorers_Sky_StoredMoney {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_StoredMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string Views_Explorers_Sky_TeamName {
            get {
                return ResourceManager.GetString("Views_Explorers_Sky_TeamName", resourceCulture);
            }
        }
    }
}
