//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyEditor.SaveEditor.UI.Avalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyEditor.SaveEditor.UI.Avalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventures.
        /// </summary>
        public static string View_ExplorersOfSky_Adventures {
            get {
                return ResourceManager.GetString("View_ExplorersOfSky_Adventures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string View_ExplorersOfSky_GeneralTab {
            get {
                return ResourceManager.GetString("View_ExplorersOfSky_GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Held Money.
        /// </summary>
        public static string View_ExplorersOfSky_HeldMoney {
            get {
                return ResourceManager.GetString("View_ExplorersOfSky_HeldMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string View_ExplorersOfSky_HistoryTab {
            get {
                return ResourceManager.GetString("View_ExplorersOfSky_HistoryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank Points.
        /// </summary>
        public static string View_ExplorersOfSky_RankPoints {
            get {
                return ResourceManager.GetString("View_ExplorersOfSky_RankPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sp. Episode Held Money.
        /// </summary>
        public static string View_ExplorersOfSky_SpEpisodeHeldMoney {
            get {
                return ResourceManager.GetString("View_ExplorersOfSky_SpEpisodeHeldMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Money.
        /// </summary>
        public static string View_ExplorersOfSky_StoredMoney {
            get {
                return ResourceManager.GetString("View_ExplorersOfSky_StoredMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string View_ExplorersOfSky_TeamName {
            get {
                return ResourceManager.GetString("View_ExplorersOfSky_TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Female.
        /// </summary>
        public static string Views_ExplorersOfSky_IsFemale {
            get {
                return ResourceManager.GetString("Views_ExplorersOfSky_IsFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Partner Gender.
        /// </summary>
        public static string Views_ExplorersOfSky_OriginalPartnerGender {
            get {
                return ResourceManager.GetString("Views_ExplorersOfSky_OriginalPartnerGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Partner Name.
        /// </summary>
        public static string Views_ExplorersOfSky_OriginalPartnerName {
            get {
                return ResourceManager.GetString("Views_ExplorersOfSky_OriginalPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Partner Pokémon.
        /// </summary>
        public static string Views_ExplorersOfSky_OriginalPartnerPkm {
            get {
                return ResourceManager.GetString("Views_ExplorersOfSky_OriginalPartnerPkm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Player Gender.
        /// </summary>
        public static string Views_ExplorersOfSky_OriginalPlayerGender {
            get {
                return ResourceManager.GetString("Views_ExplorersOfSky_OriginalPlayerGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Player Name.
        /// </summary>
        public static string Views_ExplorersOfSky_OriginalPlayerName {
            get {
                return ResourceManager.GetString("Views_ExplorersOfSky_OriginalPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Player Pokémon.
        /// </summary>
        public static string Views_ExplorersOfSky_OriginalPlayerPkm {
            get {
                return ResourceManager.GetString("Views_ExplorersOfSky_OriginalPlayerPkm", resourceCulture);
            }
        }
    }
}
