//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyEditor.SaveEditor.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClassNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClassNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyEditor.SaveEditor.Resources.ClassNames", typeof(ClassNames).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary File.
        /// </summary>
        public static string SkyEditor_SaveEditor_BinaryFile {
            get {
                return ResourceManager.GetString("SkyEditor_SaveEditor_BinaryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Pokemon (Explorers of Sky).
        /// </summary>
        public static string SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkyActivePokemon {
            get {
                return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkyActivePokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quicksave Pokemon (Explorers of Sky).
        /// </summary>
        public static string SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkyQuicksavePokemon {
            get {
                return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkyQuicksavePokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers of Sky Save File.
        /// </summary>
        public static string SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkySave {
            get {
                return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Pokemon (Explorers of Sky).
        /// </summary>
        public static string SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkyStoredPokemon {
            get {
                return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_SkyStoredPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Pokemon (Explorers of Time and Darkness).
        /// </summary>
        public static string SkyEditor_SaveEditor_MysteryDungeon_Explorers_TDActivePokemon {
            get {
                return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_TDActivePokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers of Time and Darkness Save File.
        /// </summary>
        public static string SkyEditor_SaveEditor_MysteryDungeon_Explorers_TDSave {
            get {
                return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_TDSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Pokemon (Explorers of Time and Darkness).
        /// </summary>
        public static string SkyEditor_SaveEditor_MysteryDungeon_Explorers_TDStoredPokemon {
            get {
                return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Explorers_TDStoredPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red and Blue Rescue Team Save File (North America).
        /// </summary>
        public static string SkyEditor_SaveEditor_MysteryDungeon_Rescue_RBSave {
            get {
                return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Rescue_RBSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red and Blue Rescue Team Save File (Europe).
        /// </summary>
        public static string SkyEditor_SaveEditor_MysteryDungeon_Rescue_RBSaveEU {
            get {
                return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Rescue_RBSaveEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Pokemon (Red and Blue Rescue Team).
        /// </summary>
        public static string SkyEditor_SaveEditor_MysteryDungeon_Rescue_RBStoredPokemon {
            get {
                return ResourceManager.GetString("SkyEditor_SaveEditor_MysteryDungeon_Rescue_RBStoredPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gates to Infinity game_data File (Experimental).
        /// </summary>
        public static string SkyEditor_SaveEditor_Saves_GTIGameData {
            get {
                return ResourceManager.GetString("SkyEditor_SaveEditor_Saves_GTIGameData", resourceCulture);
            }
        }
    }
}
