//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyEditor.SaveEditor.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyEditor.SaveEditor.Resources.Language", typeof(Language).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------.
        /// </summary>
        internal static string BlankPokemon {
            get {
                return ResourceManager.GetString("BlankPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeSmuMe Save File.
        /// </summary>
        internal static string DeSmuMeSaveFile {
            get {
                return ResourceManager.GetString("DeSmuMeSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery Dungeon game_data Files.
        /// </summary>
        internal static string GameDataFile {
            get {
                return ResourceManager.GetString("GameDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Held by.
        /// </summary>
        internal static string ItemToStringHeldBy {
            get {
                return ResourceManager.GetString("ItemToStringHeldBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evandixon.
        /// </summary>
        internal static string PluginAuthor {
            get {
                return ResourceManager.GetString("PluginAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky Editor&apos;s save editor for Pokémon Mystery Dungeon was made possible with help from the following researchers:
        ///
        ///evandixon - General Research
        ///matix2267 - Pokemon Structure, code for interacting with bits
        ///Grovyle91 - Item Structure, IDs of Pokemon/Items/etc
        ///Prof. 9 - Team Name character encoding
        ///Demonic722 - Misc RAM and save addresses.
        /// </summary>
        internal static string PluginCredits {
            get {
                return ResourceManager.GetString("PluginCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokémon Mystery Dungeon Save Editor Core.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Save File.
        /// </summary>
        internal static string RawSaveFile {
            get {
                return ResourceManager.GetString("RawSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        internal static string RB_Toolbox {
            get {
                return ResourceManager.GetString("RB_Toolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red and Blue Rescue Team Stored Pokemon.
        /// </summary>
        internal static string RBPkmFile {
            get {
                return ResourceManager.GetString("RBPkmFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers of Sky Active Pokemon.
        /// </summary>
        internal static string SkyPkmExFile {
            get {
                return ResourceManager.GetString("SkyPkmExFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers of Sky Stored Pokemon.
        /// </summary>
        internal static string SkyPkmFile {
            get {
                return ResourceManager.GetString("SkyPkmFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers of Sky Quicksave Pokemon.
        /// </summary>
        internal static string SkyPkmQFile {
            get {
                return ResourceManager.GetString("SkyPkmQFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Lvl. {1} {2}).
        /// </summary>
        internal static string SkyStoredPokemonToString {
            get {
                return ResourceManager.GetString("SkyStoredPokemonToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers of Time and Darkness Active Pokemon.
        /// </summary>
        internal static string TDPkmExFile {
            get {
                return ResourceManager.GetString("TDPkmExFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorers of Time and Darkness Stored Pokemon.
        /// </summary>
        internal static string TDPkmFile {
            get {
                return ResourceManager.GetString("TDPkmFile", resourceCulture);
            }
        }
    }
}
